import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import NavigationMenuBar from '@/components/Navigation/Navigation'
import { ThemeProvider as NextThemesProvider } from 'next-themes'
import ThemeDataProvider from '@/context/theme-data-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <NextThemesProvider
          attribute='class'
          enableSystem
          disableTransitionOnChange
        >
          <ThemeDataProvider>
            <NavigationMenuBar />
            <main className='container mx-auto px-8'>{children}</main>
          </ThemeDataProvider>
        </NextThemesProvider>
      </body>
    </html>
  )
}
